# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: node-connect-datadog CI 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm config set @adrise:registry https://npm.pkg.github.com
    - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GA_NPM_READER_TOKEN }}" >> .npmrc
    - run: npm ci
    - run: npm run build --if-present
